            - name: Setup Java JDK
  uses: actions/setup-java@v5.2.0
  with:
    # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
    java-version: 26 # optional
    # The path to the `.java-version` file. See examples of supported syntax in README file
    java-version-file: # optional
    # Java distribution. See the list of supported distributions in README file
    distribution: jdk
    # The package type (jdk, jre, jdk+fx, jre+fx)
    java-package: # optional, default is jdk
    # The architecture of the package (defaults to the action runner's architecture)
    architecture: # optional
    # Path to where the compressed JDK is located
    jdkFile: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec
    check-latest: # optional
    # ID of the distributionManagement repository in the pom.xml file. Default is `github`
    server-id: # optional, default is github
    # Environment variable name for the username for authentication to the Apache Maven repository. Default is $GITHUB_ACTOR
    server-username: # optional, default is GITHUB_ACTOR
    # Environment variable name for password or token for authentication to the Apache Maven repository. Default is $GITHUB_TOKEN
    server-password: # optional, default is GITHUB_TOKEN
    # Path to where the settings.xml file will be written. Default is ~/.m2.Powershell
    settings-path: # optional
    # Overwrite the settings.xml file if it exists. Default is "true".
    overwrite-settings: # optional, default is true
    # GPG private key to import. Default is empty string.
    gpg-private-key: # optional
    # Environment variable name for the GPG private key passphrase. Default is $GPG_PASSPHRASE.
    gpg-passphrase: # optional
    # Name of the build platform to cache dependencies. It can be "maven", "gradle" or "sbt".
    cache: # optional
    # The path to a dependency file: pom.xml, build.gradle, build.sbt, etc. This option can be used with the `cache` option. If this option is omitted, the action searches for the dependency file in the entire repository. This option supports wildcards and a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
    # Workaround to pass job status to post job step. This variable is not intended for manual setting
    job-status: # optional, default is ${{ job.status }}
    # The token used to authenticate when fetching version manifests hosted on github.com, such as for the Microsoft Build of OpenJDK. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Name of Maven Toolchain ID if the default name of "${distribution}_${java-version}" is not wanted. See examples of supported syntax in Advanced Usage file
    mvn-toolchain-id: # optional
    # Name of Maven Toolchain Vendor if the default name of "${distribution}" is not wanted. See examples of supported syntax in Advanced Usage file
    mvn-toolchain-vendor: # optional


                - name: Install Windows SDK
  # You may pin to the exact commit or the version.
  # uses: Lamparter/Install-WindowsSdk@f0cc45f4968edf1472331d4b8cdd22c063dbb11e
  uses: Lamparter/Install-WindowsSdk@v1.0.0
  with:
    # The build number of the Windows SDK to install.
    buildNumber: 10.0.28000.1839<

              - name: Install powershell
  # You may pin to the exact commit or the version.
  # uses: cakhanif/action-install-powershell@9287716f19f5547fb975cd59dc23b286fabffdf8
  uses: cakhanif/action-install-powershell@v1
          
              - name: Setup Python
  uses: actions/setup-python@v6.2.0
  with:
    # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
    python-version: 3 # optional
    # File containing the Python version to use. Example: .python-version
    python-version-file: # optional
    # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
    cache: # optional
    # The target architecture (x86, x64, arm64) of the Python or PyPy interpreter.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # The token used to authenticate when fetching Python distributions from https://github.com/actions/python-versions. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify the path to dependency files. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
    # Set this option if you want the action to update environment variables.
    update-environment: # optional, default is true
    # When 'true', a version range passed to 'python-version' input will match prerelease versions if no GA versions are found. Only 'x.y' version range is supported for CPython.
    allow-prereleases: # optional
    # When 'true', use the freethreaded version of Python.
    freethreaded: # optional
    # Used to specify the version of pip to install with the Python. Supported format: major[.minor][.patch].
    pip-version: # optional
    # Used to specify the packages to install with pip after setting up Python. Can be a requirements file or package names.
    pip-install: pillow # optional

  
